chore(fix): ci - add checksum and s3 upload (#285)

diff --git a/.github/workflows/build_cli.yml b/.github/workflows/build_cli.yml
--- a/.github/workflows/build_cli.yml
+++ b/.github/workflows/build_cli.yml
@@ -17,6 +17,8 @@ env:
   CARGO: cargo
   # CARGO_OPTIONS: "--verbose"
   CARGO_OPTIONS: "--release"
+  # tari_launchpad_{network}_{network_version}
+  TBN_FILENAME: "tari_launchpad_cli"
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -48,8 +50,8 @@ jobs:
           #
           # Setup the json build matrix
           matrix=$(echo ${matrix_selection} | jq -s -c '{"builds": .}')
-          echo $matrix
-          echo $matrix | jq .
+          echo ${matrix}
+          echo ${matrix} | jq .
           echo "matrix=${matrix}" >> $GITHUB_OUTPUT
 
   matrix-check:
@@ -65,13 +67,16 @@ jobs:
       - name: Check matrix definition
         run: |
           matrix='${{ needs.matrix-prep.outputs.matrix }}'
-          echo $matrix
-          echo $matrix | jq .
-          echo $matrix | json2yaml
+          echo ${matrix}
+          echo ${matrix} | jq .
+          echo ${matrix} | json2yaml
 
   builds:
     name: Building ${{ matrix.builds.name }} on ${{ matrix.builds.runs-on }}
     needs: matrix-prep
+    outputs:
+      TARI_NETWORK_DIR: ${{ steps.set-tari-vars.outputs.TARI_NETWORK_DIR }}
+      TARI_NETWORK_VERSION: ${{ steps.set-tari-vars.outputs.TARI_NETWORK_VERSION }}
     strategy:
       fail-fast: false
       matrix: ${{ fromJson(needs.matrix-prep.outputs.matrix) }}
@@ -88,6 +93,17 @@ jobs:
           components: rustfmt, clippy
           toolchain: ${{ matrix.builds.rust }}
           targets: ${{ matrix.builds.target }}
+
+      - name: Declare Global Variables 4 GHA ${{ github.event_name }}
+        id: set-tari-vars
+        shell: bash
+        run: |
+          # multiNet based on git branch
+          echo "TARI_NETWORK_DIR=${{ github.ref_name }}" >> $GITHUB_ENV
+          echo "TARI_NETWORK_DIR=${{ github.ref_name }}" >> $GITHUB_OUTPUT
+          TARI_NETWORK_VERSION=$(cargo tree -p tari-lp-cli -i tari_core --locked | head -n1 | cut -d " " -f 2)
+          echo "TARI_NETWORK_VERSION=${TARI_NETWORK_VERSION}" >> $GITHUB_ENV
+          echo "TARI_NETWORK_VERSION=${TARI_NETWORK_VERSION}" >> $GITHUB_OUTPUT
 
       - name: Install Linux dependencies - Ubuntu
         if: ${{ startsWith(runner.os,'Linux') && ( ! matrix.builds.cross ) }}
@@ -190,84 +206,87 @@ jobs:
           echo "cross flag: ${{ matrix.builds.cross }}"
 
       - name: Build release binaries
-        # can't use bash for windows build, perl openssl breakage
+        # can't use bash for windows build, perl breakage for openssl
         # shell: bash
-        run: |
-          ${{ env.CARGO }} build ${{ env.CARGO_OPTIONS }} --target ${{ matrix.builds.target }} --bin tari-lp-cli ${{ matrix.builds.flags }} --locked
+        # don't mess with indentation (readability)
+        run: >
+          ${{ env.CARGO }} build ${{ env.CARGO_OPTIONS }}
+          --target ${{ matrix.builds.target }}
+          --bin tari-lp-cli
+          ${{ matrix.builds.flags }} --locked
 
-      - name: Archive and Checksum Binaries
-        if: ${{ false }}
+      - name: Setup BINFILE Env
         shell: bash
         run: |
+          BINFILE="${TBN_FILENAME}-${TARI_NETWORK_DIR}-${TARI_NETWORK_VERSION}-${{ matrix.builds.name }}${TBN_EXT}"
+          echo "Bin env is ${BINFILE}"
+          echo "BINFILE=${BINFILE}" >> $GITHUB_ENV
+
+      - name: Archive and Checksum Binaries
+        shell: bash
+        run: |
+          # set -xo pipefail
           echo "Archive ${{ env.BINFILE }} too ${{ env.BINFILE }}.zip"
-          cd "$GITHUB_WORKSPACE${{ env.TBN_DIST }}"
+          mkdir -vp "${GITHUB_WORKSPACE}/dist/"
+          cd "${GITHUB_WORKSPACE}/dist/"
+          cp -v "${GITHUB_WORKSPACE}/target/${{ matrix.builds.target }}/release/tari-lp-cli${{ env.TBN_EXT }}" ${{ env.BINFILE }}
           echo "Compute files shasum"
           ${SHARUN} * >> "${{ env.BINFILE }}.sha256"
           echo "Show the shasum"
           cat "${{ env.BINFILE }}.sha256"
           echo "Checksum verification for files is "
           ${SHARUN} --check "${{ env.BINFILE }}.sha256"
-          7z a "${{ env.BINFILE }}.zip" *
-          echo "Compute archive shasum"
-          ${SHARUN} "${{ env.BINFILE }}.zip" >> "${{ env.BINFILE }}.zip.sha256"
-          echo "Show the shasum"
-          cat "${{ env.BINFILE }}.zip.sha256"
-          echo "Checkum verification archive is "
-          ${SHARUN} --check "${{ env.BINFILE }}.zip.sha256"
+#          7z a "${{ env.BINFILE }}.zip" *
+#          echo "Compute archive shasum"
+#          ${SHARUN} "${{ env.BINFILE }}.zip" >> "${{ env.BINFILE }}.zip.sha256"
+#          echo "Show the shasum"
+#          cat "${{ env.BINFILE }}.zip.sha256"
+#          echo "Checksum verification archive is "
+#          ${SHARUN} --check "${{ env.BINFILE }}.zip.sha256"
 
       - name: Artifact upload for Archive
         uses: actions/upload-artifact@v4
         with:
-          name: "tari-lp-cli-${{ matrix.builds.name }}"
-          path: "${{ github.workspace }}/target/${{ matrix.builds.target }}/release/tari-lp-cli${{ env.TBN_EXT }}"
-
-      - name: Sync dist to S3 - Bash
-        continue-on-error: true # Don't break if s3 upload fails
-        if: ${{ env.AWS_SECRET_ACCESS_KEY != '' && matrix.builds.runs-on != 'self-hosted' }}
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          DEST_DIR: "${{ env.S3_DEST_OVERRIDE }}${{ env.PLATFORM_SPECIFIC_DIR }}/${{ env.TARI_NETWORK_DIR }}/"
-          S3CMD: "cp"
-          S3OPTIONS: '--recursive --exclude "*" --include "*.zip*" --include "*.pkg*" --include "*installer.exe*"'
-        shell: bash
-        run: |
-          echo "Starting upload ... ${{ env.MTS_SOURCE }}"
-          ls -al ${{ env.MTS_SOURCE }}
-
-          aws --version
-
-          aws s3 ${{ env.S3CMD }} --region ${{ secrets.AWS_REGION }} \
-            "${{ env.MTS_SOURCE }}" \
-            s3://${{ secrets.AWS_S3_BUCKET }}/${{ env.DEST_DIR }} \
-            ${{ env.S3OPTIONS }}
-
-          if [[ "${{ github.ref }}" =~ refs\/tags\/v* ]]; then
-            echo "Copy tags to latest s3"
-            aws s3 ${{ env.S3CMD }} --region ${{ secrets.AWS_REGION }} \
-              "${{ env.MTS_SOURCE }}" \
-              s3://${{ secrets.AWS_S3_BUCKET }}/current/${{ env.DEST_DIR }} \
-              ${{ env.S3OPTIONS }}
-
-            aws s3 rm --region ${{ secrets.AWS_REGION }} \
-              s3://${{ secrets.AWS_S3_BUCKET }}/latest/${{ env.DEST_DIR }} \
-              --recursive --include "*"
-
-            aws s3 ${{ env.S3CMD }} --region ${{ secrets.AWS_REGION }} \
-              "${{ env.MTS_SOURCE }}" \
-              s3://${{ secrets.AWS_S3_BUCKET }}/latest/${{ env.DEST_DIR }} \
-              ${{ env.S3OPTIONS }}
-          fi
+          name: "${{ env.BINFILE }}"
+          path: ${{ github.workspace }}/dist/
 
   create-release:
+    # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
     runs-on: ubuntu-latest
     needs: builds
-    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+    env:
+      TARI_NETWORK_DIR: ${{ needs.builds.outputs.TARI_NETWORK_DIR }}
+      TARI_NETWORK_VERSION: ${{ needs.builds.outputs.TARI_NETWORK_VERSION }}
+
     steps:
       - name: Download binaries
         uses: actions/download-artifact@v4
+        with:
+          path: ${{ env.TBN_FILENAME }}
+          pattern: "${{ env.TBN_FILENAME }}*"
+          merge-multiple: true
+
+      - name: Verify checksums and Prep Uploads
+        continue-on-error: true
+        shell: bash
+        working-directory: ${{ env.TBN_FILENAME }}
+        run: |
+          # set -xo pipefail
+          sudo apt-get update
+          sudo apt-get --no-install-recommends --assume-yes install dos2unix
+          ls -alhtR
+          if [ -f "${{ env.TBN_FILENAME }}-${{ env.TARI_NETWORK_VERSION }}.txt.sha256-unsigned" ] ; then
+            rm -fv "${{ env.TBN_FILENAME }}-${{ env.TARI_NETWORK_VERSION }}.txt.sha256-unsigned"
+          fi
+          # Merge all sha256 files into one
+          find . -name "*.sha256" -type f -print | xargs cat >> "${{ env.TBN_FILENAME }}-${{ env.TARI_NETWORK_VERSION }}.txt.sha256-unsigned"
+          dos2unix --quiet "${{ env.TBN_FILENAME }}-${{ env.TARI_NETWORK_VERSION }}.txt.sha256-unsigned"
+          cat "${{ env.TBN_FILENAME }}-${{ env.TARI_NETWORK_VERSION }}.txt.sha256-unsigned"
+          sha256sum --ignore-missing --check "${{ env.TBN_FILENAME }}-${{ env.TARI_NETWORK_VERSION }}.txt.sha256-unsigned"
+          ls -alhtR
 
       - name: Create release
+        if: ${{ false }}
         uses: ncipollo/release-action@v1
         with:
           artifacts: "tari_*/**/*"
@@ -277,3 +296,46 @@ jobs:
           allowUpdates: true
           updateOnlyUnreleased: true
           replacesArtifacts: true
+
+      - name: Sync assets to S3
+        continue-on-error: true # Don't break if s3 upload fails
+        # if: ${{ env.AWS_SECRET_ACCESS_KEY != '' && matrix.builds.runs-on != 'self-hosted' }}
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          S3CMD: "cp"
+          S3OPTIONS: '--recursive --exclude "*" --include "*.sha256*" --include "*.zip*" --include "*.pkg*" --include "*installer.exe*"'
+        shell: bash
+        working-directory: ${{ env.TBN_FILENAME }}
+        run: |
+          echo "Upload processing ..."
+          ls -alhtR
+          echo "Clean up"
+          # Bash check if file with wildcards, does not work as expected
+          # if [ -f ${{ env.TBN_FILENAME }}*diag-utils* ] ; then
+          if ls ${{ env.TBN_FILENAME }}*diag-utils* > /dev/null 2>&1 ; then
+            rm -fv ${{ env.TBN_FILENAME }}*diag-utils*
+          fi
+          echo "Folder setup"
+          if ls ${{ env.TBN_FILENAME }}*linux* > /dev/null 2>&1 ; then
+            mkdir -p "linux/${{ env.TARI_NETWORK_DIR }}/"
+            mv -v ${{ env.TBN_FILENAME }}*linux* "linux/${{ env.TARI_NETWORK_DIR }}/"
+          fi
+          if ls ${{ env.TBN_FILENAME }}*macos* > /dev/null 2>&1 ; then
+            mkdir -p "osx/${{ env.TARI_NETWORK_DIR }}/"
+            mv -v ${{ env.TBN_FILENAME }}*macos* "osx/${{ env.TARI_NETWORK_DIR }}/"
+          fi
+          if ls ${{ env.TBN_FILENAME }}*windows* > /dev/null 2>&1 ; then
+            mkdir -p "windows/${{ env.TARI_NETWORK_DIR }}/"
+            mv -v ${{ env.TBN_FILENAME }}*windows* "windows/${{ env.TARI_NETWORK_DIR }}/"
+          fi
+          ls -alhtR
+          aws --version
+          echo "ls current"
+          aws s3 ls --region ${{ secrets.AWS_REGION }} \
+            s3://${{ secrets.AWS_S3_BUCKET }}/launchpad/current/
+          echo "Upload current"
+          aws s3 ${{ env.S3CMD }} --region ${{ secrets.AWS_REGION }} \
+            . \
+            s3://${{ secrets.AWS_S3_BUCKET }}/launchpad/current/ \
+            ${{ env.S3OPTIONS }}
